# Generated by Django 5.2.9 on 2026-02-10 11:17

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_fts_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="projects/images/",
                validators=[apps.core.validators.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="projectdocument",
            name="file",
            field=models.FileField(
                upload_to="projects/documents/%Y/%m/",
                validators=[apps.core.validators.validate_document_file],
            ),
        ),
    ]
