# Generated by Django 5.2.9 on 2026-02-10 11:17

import apps.accounts.models
import apps.core.validators
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.models.SoftDeleteUserManager()),
                ("all_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                upload_to="avatars/",
                validators=[apps.core.validators.validate_image_file],
            ),
        ),
    ]
