# Generated by Django 5.2.9 on 2026-02-10 11:58

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesetting",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="site/",
                validators=[apps.core.validators.validate_image_file],
            ),
        ),
    ]
