# Generated by Django 5.2.9 on 2026-02-10 14:33

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_sitesetting_image_validator"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=150)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("direction", "Direction Générale"),
                            ("etudes", "Bureau d'Études"),
                            ("laboratoire", "Laboratoire"),
                            ("admin", "Administration"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to="team/",
                        validators=[apps.core.validators.validate_image_file],
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("order", models.PositiveIntegerField(default=0)),
                ("published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Membre de l'équipe",
                "verbose_name_plural": "Membres de l'équipe",
                "ordering": ["department", "order", "last_name"],
            },
        ),
    ]
