# Generated by Django 5.2.9 on 2026-02-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_portal_enhancements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="projectcomment",
            name="content",
            field=models.TextField(max_length=10000),
        ),
    ]
