# Generated by Django 5.2.9 on 2026-02-10 11:17

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_fts_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="articles/images/",
                validators=[apps.core.validators.validate_image_file],
            ),
        ),
    ]
